name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: gradle:8.10.1-jdk22
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: ./.github/actions/gradle
        with:
          command: test
